# DATA PREPROCESSING

#Pandas Kutubxonasini chaqirib olam,iz

In [1]:
import pandas as pd

#Data Setni o`ng tamonga o`tkazib olamiz

In [2]:
df = pd.read_csv('global_earthquake.csv')

#Data set haqida malumot olamiz

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 23409 entries, 0 to 23408
Data columns (total 21 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   Date                        23409 non-null  object
 1   Time                        23409 non-null  object
 2   Latitude                    23409 non-null  float64
 3   Longitude                   23409 non-null  float64
 4   Type                        23409 non-null  object
 5   Depth                       23409 non-null  float64
 6   Depth Error                 4460 non-null   float64
 7   Depth Seismic Stations      7096 non-null   float64
 8   Magnitude                   23409 non-null  float64
 9   Magnitude Type              23406 non-null  object
 10  Magnitude Error             327 non-null    float64
 11  Magnitude Seismic Stations  2564 non-null   float64
 12  Azimuthal Gap               7298 non-null   float64
 13  Horizontal Distance         1604 non-null   float64
 14  Horizontal Error            1156 non-null   float64
 15  Root Mean Square            17350 non-null  float64
 16  ID                          23409 non-null  object
 17  Source                      23409 non-null  object
 18  Location Source             23409 non-null  object
 19  Magnitude Source            23409 non-null  object
 20  Status                      23409 non-null  object
dtypes: float64(12), object(9)
memory usage: 3.8+ MB

#Data setni eng boshidan 10 ta qator chiqaramiz

In [3]:
df.head(10)

,Date,Time,Latitude,Longitude,Type,Depth,Depth Error,Depth Seismic Stations,Magnitude,Magnitude Type,...,Magnitude Seismic Stations,Azimuthal Gap,Horizontal Distance,Horizontal Error,Root Mean Square,ID,Source,Location Source,Magnitude Source,Status
0,01/02/1965,13:44:18,19.246,145.616,Earthquake,131.6,NaN,NaN,6.0,MW,...,NaN,NaN,NaN,NaN,NaN,ISCGEM860706,ISCGEM,ISCGEM,ISCGEM,Automatic
1,01/04/1965,11:29:49,1.863,127.352,Earthquake,80.0,NaN,NaN,5.8,MW,...,NaN,NaN,NaN,NaN,NaN,ISCGEM860737,ISCGEM,ISCGEM,ISCGEM,Automatic
2,01/05/1965,18:05:58,-20.579,-173.972,Earthquake,20.0,NaN,NaN,6.2,MW,...,NaN,NaN,NaN,NaN,NaN,ISCGEM860762,ISCGEM,ISCGEM,ISCGEM,Automatic
3,01/08/1965,18:49:43,-59.076,-23.557,Earthquake,15.0,NaN,NaN,5.8,MW,...,NaN,NaN,NaN,NaN,NaN,ISCGEM860856,ISCGEM,ISCGEM,ISCGEM,Automatic
4,01/09/1965,13:32:50,11.938,126.427,Earthquake,15.0,NaN,NaN,5.8,MW,...,NaN,NaN,NaN,NaN,NaN,ISCGEM860890,ISCGEM,ISCGEM,ISCGEM,Automatic
5,01/10/1965,13:36:32,-13.405,166.629,Earthquake,35.0,NaN,NaN,6.7,MW,...,NaN,NaN,NaN,NaN,NaN,ISCGEM860922,ISCGEM,ISCGEM,ISCGEM,Automatic
6,01/12/1965,13:32:25,27.357,87.867,Earthquake,20.0,NaN,NaN,5.9,MW,...,NaN,NaN,NaN,NaN,NaN,ISCGEM861007,ISCGEM,ISCGEM,ISCGEM,Automatic
7,01/15/1965,23:17:42,-13.309,166.212,Earthquake,35.0,NaN,NaN,6.0,MW,...,NaN,NaN,NaN,NaN,NaN,ISCGEM861111,ISCGEM,ISCGEM,ISCGEM,Automatic
8,01/16/1965,11:32:37,-56.452,-27.043,Earthquake,95.0,NaN,NaN,6.0,MW,...,NaN,NaN,NaN,NaN,NaN,ISCGEMSUP861125,ISCGEMSUP,ISCGEM,ISCGEM,Automatic
9,01/17/1965,10:43:17,-24.563,178.487,Earthquake,565.0,NaN,NaN,5.8,MW,...,NaN,NaN,NaN,NaN,NaN,ISCGEM861148,ISCGEM,ISCGEM,ISCGEM,Automatic

#Data Setni eng oxiridan 10 ta qator chiqaramiz

In [4]:
df.tail(10)

,Date,Time,Latitude,Longitude,Type,Depth,Depth Error,Depth Seismic Stations,Magnitude,Magnitude Type,...,Magnitude Seismic Stations,Azimuthal Gap,Horizontal Distance,Horizontal Error,Root Mean Square,ID,Source,Location Source,Magnitude Source,Status
23399,12/24/2016,03:58:55,-5.1460,153.5166,Earthquake,30.00,1.8,NaN,5.8,MWW,...,NaN,14.00,1.648,7.0,0.8500,US10007MFP,US,US,US,Reviewed
23400,12/25/2016,14:22:27,-43.4029,-73.9395,Earthquake,38.00,1.9,NaN,7.6,MWW,...,NaN,29.00,0.351,6.8,0.8000,US10007MN3,US,US,US,Reviewed
23401,12/25/2016,14:32:13,-43.4810,-74.4771,Earthquake,14.93,3.3,NaN,5.6,MB,...,83.0,96.00,0.697,7.1,0.5200,US10007MNB,US,US,US,Reviewed
23402,12/27/2016,23:20:56,45.7192,26.5230,Earthquake,97.00,1.8,NaN,5.6,MWW,...,NaN,14.00,0.465,5.1,0.7800,US10007N3R,US,US,US,Reviewed
23403,12/28/2016,08:18:01,38.3754,-118.8977,Earthquake,10.80,1.3,34.0,5.6,ML,...,20.0,35.86,0.132,NaN,0.1988,NN00570709,NN,NN,NN,Reviewed
23404,12/28/2016,08:22:12,38.3917,-118.8941,Earthquake,12.30,1.2,40.0,5.6,ML,...,18.0,42.47,0.120,NaN,0.1898,NN00570710,NN,NN,NN,Reviewed
23405,12/28/2016,09:13:47,38.3777,-118.8957,Earthquake,8.80,2.0,33.0,5.5,ML,...,18.0,48.58,0.129,NaN,0.2187,NN00570744,NN,NN,NN,Reviewed
23406,12/28/2016,12:38:51,36.9179,140.4262,Earthquake,10.00,1.8,NaN,5.9,MWW,...,NaN,91.00,0.992,4.8,1.5200,US10007NAF,US,US,US,Reviewed
23407,12/29/2016,22:30:19,-9.0283,118.6639,Earthquake,79.00,1.8,NaN,6.3,MWW,...,NaN,26.00,3.553,6.0,1.4300,US10007NL0,US,US,US,Reviewed
23408,12/30/2016,20:08:28,37.3973,141.4103,Earthquake,11.94,2.2,NaN,5.5,MB,...,428.0,97.00,0.681,4.5,0.9100,US10007NTD,US,US,US,Reviewed

# Data Setda tushirib qoldirilgan ustunlarni aniqlaymiz

In [6]:
df.isnull().sum()

Date                              0
Time                              0
Latitude                          0
Longitude                         0
Type                              0
Depth                             0
Depth Error                   18949
Depth Seismic Stations        16313
Magnitude                         0
Magnitude Type                    3
Magnitude Error               23082
Magnitude Seismic Stations    20845
Azimuthal Gap                 16111
Horizontal Distance           21805
Horizontal Error              22253
Root Mean Square               6059
ID                                0
Source                            0
Location Source                   0
Magnitude Source                  0
Status                            0
dtype: int64

# Mean (numerical) - orqali to`ldirib ko`ramiz  // DEPTH ERROR USTUNI

In [7]:
df['Depth Error'].fillna(df['Depth Error'].mean(), inplace=True)

C:\Users\Rasulbek_Ruzmetov\AppData\Local\Temp\ipykernel_11912\4092775055.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Depth Error'].fillna(df['Depth Error'].mean(), inplace=True)

# Natijani ko`ramiz

In [9]:
df.isnull().sum()

Date                              0
Time                              0
Latitude                          0
Longitude                         0
Type                              0
Depth                             0
Depth Error                       0
Depth Seismic Stations        16313
Magnitude                         0
Magnitude Type                    3
Magnitude Error               23082
Magnitude Seismic Stations    20845
Azimuthal Gap                 16111
Horizontal Distance           21805
Horizontal Error              22253
Root Mean Square               6059
ID                                0
Source                            0
Location Source                   0
Magnitude Source                  0
Status                            0
dtype: int64

# Mode - orqali to`ldirib ko`ramiz // Azimuthal Gap USTUNI

In [10]:
df['Azimuthal Gap'].fillna(df['Azimuthal Gap'].mode()[0], inplace=True)

C:\Users\Rasulbek_Ruzmetov\AppData\Local\Temp\ipykernel_11912\4280031982.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Azimuthal Gap'].fillna(df['Azimuthal Gap'].mode()[0], inplace=True)

# Natijani ko`ramiz

In [11]:
df.isnull().sum()

Date                              0
Time                              0
Latitude                          0
Longitude                         0
Type                              0
Depth                             0
Depth Error                       0
Depth Seismic Stations        16313
Magnitude                         0
Magnitude Type                    3
Magnitude Error               23082
Magnitude Seismic Stations    20845
Azimuthal Gap                     0
Horizontal Distance           21805
Horizontal Error              22253
Root Mean Square               6059
ID                                0
Source                            0
Location Source                   0
Magnitude Source                  0
Status                            0
dtype: int64

# Median - orqali to`ldirib ko`ramiz // Horizontal Distance USTUNI

In [13]:
df['Horizontal Distance'].fillna(df['Horizontal Distance'].median(), inplace=True)

C:\Users\Rasulbek_Ruzmetov\AppData\Local\Temp\ipykernel_11912\2758373675.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Horizontal Distance'].fillna(df['Horizontal Distance'].median(), inplace=True)

# Natijani ko`ramiz

In [14]:
df.isnull().sum()

Date                              0
Time                              0
Latitude                          0
Longitude                         0
Type                              0
Depth                             0
Depth Error                       0
Depth Seismic Stations        16313
Magnitude                         0
Magnitude Type                    3
Magnitude Error               23082
Magnitude Seismic Stations    20845
Azimuthal Gap                     0
Horizontal Distance               0
Horizontal Error              22253
Root Mean Square               6059
ID                                0
Source                            0
Location Source                   0
Magnitude Source                  0
Status                            0
dtype: int64